webapp/generator_app/urls.py
from django.urls import path
from . import views

app_name="generator_app"

urlpatterns = [
    path('', views.landingPage, name='landingPage'),
    path('generator/',views.generatePage,name='generator'),
    path('generate_description/',views.generate_description,name="generate_description"),
    path('generate_description_by_scene/',views.generateDescriptionByScene,name="generate_description_by_scene"),
    path('generate_audio/',views.generate_audio,name="generate_audio"),
    
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('generator_app.urls',namespace='generator_app')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/generator_app/models.py
from django.db import models

# Create your models here.

webapp/generator_app/views.py
import PIL.Image
from django.shortcuts import render
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from rest_framework import status
from django.http import JsonResponse,HttpResponse
from gtts import gTTS
from django.views.decorators.csrf import csrf_exempt
import os
import sys
import PIL
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
from .generator import Generator
from .by_scene_generator import BySceneGenerator

# Create your views here.

def landingPage(request):
    return render(request,'index.html')

def generatePage(request):
    
    if request.method=="POST":
        file_to_process=request.FILES.get('input_file')
        print(file_to_process)
    return render(request,'generation_page.html')

@csrf_exempt
def generate_description(request):
    if request.method == "POST":
        file_object=request.FILES.get('file')
        if not file_object:
            return JsonResponse({"error": "No file uploaded"}, status=status.HTTP_400_BAD_REQUEST)
        else:
            with open(f"test_uploads/{file_object.name}", "wb+") as destination:
                for chunk in file_object.chunks():
                    destination.write(chunk)
                print("File Saved!")
            
            # get the file object stored in test_uploads folder to pass 
            # to the function that generates the description
            
            file_path = f"test_uploads/{file_object.name}"
            file_extension=Path(file_object.name).suffix
            
            img_extensions = ['.jpg', '.png', '.jpeg']
            vid_extensions = ['.mp4', '.avi']
            
            generator=Generator()

            
            if os.path.isfile(file_path):
                print("File exists")
                if file_extension.lower() in img_extensions:
                    print("its an image file here")                
                    caption=generator.gen_caption(file_path,as_string=True,by_scene=False)
                    return JsonResponse({"message":caption,"vidFile":False,"filename":file_object.name}, status=status.HTTP_200_OK)
 
                else:
                    if file_extension.lower() in vid_extensions:
                        caption=generator.gen_caption(file_path,as_string=True,by_scene=False)
                        print("its a video file here")                
                        caption=generator.gen_caption(file_path,as_string=True,by_scene=False)
                        return JsonResponse({"message":caption,"vidFile":True,"filename":file_object.name}, status=status.HTTP_200_OK)
                    else:
                        return JsonResponse({"error": f"The current model can not process {file_extension} files!"}, status=status.HTTP_400_BAD_REQUEST)

            else:
                print("File does not exist")
                return JsonResponse({"error": "No file found to pass for description generation"}, status=status.HTTP_400_BAD_REQUEST)

@csrf_exempt
def generateDescriptionByScene(request):
    if request.method == "POST":
        print("Generate Descriptions by scene!")
        file_object=request.FILES.get('file')
        if not file_object:
            return JsonResponse({"error": "No file uploaded"}, status=status.HTTP_400_BAD_REQUEST)
        else:
            with open(f"test_uploads/{file_object.name}", "wb+") as destination:
                for chunk in file_object.chunks():
                    destination.write(chunk)
                print("File Saved!")
            
            # get the file object stored in test_uploads folder to pass 
            # to the function that generates the description
            
            file_path = f"test_uploads/{file_object.name}"
            file_extension=Path(file_object.name).suffix
            
            img_extensions = ['.jpg', '.png', '.jpeg']
            vid_extensions = ['.mp4', '.avi']

            if file_extension in vid_extensions:
                by_scene_generator=BySceneGenerator()
                captions,scene_change_timecodes=by_scene_generator.generate_description(video_path=file_path,as_string=True,byScene=True)
                
                return JsonResponse({"captions":captions,"timecodes":scene_change_timecodes,"filename":file_object.name}, status=status.HTTP_200_OK)
            else:
                return JsonResponse({"message":"Can not generate descriptions by scene!"}, status=status.HTTP_200_OK)

            
            
        return JsonResponse({"message":"Generating Descriptions by scene!"}, status=status.HTTP_200_OK)
    else:
        return JsonResponse({"error": "No file found to pass for description generation"}, status=status.HTTP_400_BAD_REQUEST)


def generate_audio(request):
    captions=request.GET.get("captions","")
    filename=request.GET.get("file_name")
    
    if not captions:
        return JsonResponse({"error": "No captions provided for audio generation"}, status=400)
    try:
        # Generate audio from captions using gTTS
        tts = gTTS(text=captions, lang='en')
        audio_file_path = f"test_results/{filename}_generated_audio.mp3"
        tts.save(audio_file_path)

        # Serve the audio file as a response
        with open(audio_file_path, 'rb') as audio_file:
            response = HttpResponse(audio_file.read(), content_type="audio/mpeg")
            response['Content-Disposition'] = f'inline; filename="{audio_file_path}"'
            return response

    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)
    

webapp/generator_app/templates/index.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Landing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/typewriter-effect@2.18.0/dist/core.js"></script>
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background: linear-gradient(201deg, rgba(255, 0, 0, 1) 7%, rgba(148, 89, 144, 1) 50%, rgba(0, 211, 255, 1) 100%);
            /* Linear gradient background */
            color: #e0e0e0;
            /* Light text */
            flex-direction: column;
            padding: 20px;
        }

        a {
            text-decoration: none;
        }

        h3 {
            color: #fff;
        }

        .button {
            width: 12em;
            padding: 1em;
            color: #fff;
            background-color: salmon;
            font-weight: 600;
            cursor: pointer;
            position: relative;
            bottom: 0px;
            right: 0px;
            box-shadow: 8px 8px 0px red;
            text-align: center;
            transition: all .25s ease-in-out;
        }

        .button:hover {
            bottom: -4px;
            right: -4px;
            box-shadow: 4px 4px 0px red;
            transform: scale(1.05);
        }

        .button:active {
            bottom: -7px;
            right: -7px;
            box-shadow: 1px 1px 0px red;
        }

        .img-container {
            animation: fadeIn 2s;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(-10%);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        #typewriter-text {
            color: #c0c0c0;
            font-weight: 600;
            font-size: 1.5em;
            font-style: italic;
        }
    </style>
</head>

<body>
    <div class="container col-xxl-8 px-4">
        <div class="row flex-lg-row-reverse align-items-center g-5">
            <div class="col-10 col-sm-8 col-lg-6 img-container">
                <img src="{% static "blind_man3.png" %}"
                    class="d-block mx-lg-auto img-fluid rounded shadow" alt="Blind man" loading="lazy">
            </div>
            <div class="col-lg-6">
                <h3 class="display-5 fw-bold lh-1 mb-3">Scene Description Generator for Visually
                    Impaired People from Multi-Modal Input with Spatial AI</h3>
                <p class="lead" id="typewriter-text"></p>
                <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                    <a href="{% url 'generator_app:generator' %}">
                        <div class="button">Start Using?</div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var app = document.getElementById('typewriter-text');

            var typewriter = new Typewriter(app, {
                loop: false,
                delay: 20,
            });

            typewriter.typeString('An application that generates contextual descriptions for real-world scenes')
                .pauseFor(500)
                .deleteAll()
                .typeString('Helping visually impaired people understand their surroundings with Spatial AI.')
                .start();
        });
    </script>
</body>

</html>